version: '3'

services:

  #############################################################
  ######################### DATABASES #########################
  #############################################################

  db-despesas:
    container_name: db-despesas
    image: postgres:9.6
    restart: always
    hostname: db-despesas
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: despesas
      POSTGRES_USER: despesas
      POSTGRES_PASSWORD: despesas
      PGDATA: /tmp
    volumes:
      - ./docker/postgres/data-despesa:/var/lib/postgresql/data

  #############################################################
  ######################### SERVICES ##########################
  #############################################################

  despesas-service:
    container_name: despesas-service
    image: despesas-service
    restart: always
    links:
      - db-despesas
    ports:
      - "8080:8080"
    environment:
      DB_ALIAS: db-despesas